### ISSUE TITLE
The colors instead of only the color's names

### ISSUE THREAD

**Issue by oxydron** [fguillot/kanboard#1071]
Hi, very good people!

It's a very good feature to have more colors do use on tasks, but show only the color's names is problematic sometimes.

Show the colors too :D

Best regards,
Ben Hur

**Comment by spinus** [comment]
+1, and I would say it could be just a bar with colors instead of dropdown which is horrible.

I thought also maybe would be great to actually merge colors and categories, it basically the same function (for me), it just about to make a distinction for a cards. Currently I have to add a category and color (always the same in my case) to cards (two dropdowns :( ). Please consider this.

**Comment by shimza** [comment]
Please do not combine the colors and categories.
We use them for very different purposes.

**Comment by spinus** [comment]
@shimza that is new to me, may be interesting. Could you explain the workflow?

So another idea would be to add "colorful categories labels" for cards instead for changing color of whole card, that seems better?

I came up with this idea because colors-only approach for me lack some information. You know that cards are different but you don't know why and you have no idea how to check it. It would be nice to have some explanation what is "blue" and what is "orange". So maybe we can have labels to colors (per project)?

**Comment by shimza** [comment]
We use some colours for status green orange and red.

Others for type of client or idea before its active... Eg blue...

Categories we use for location names such as Bronx Brooklyn

**Comment by deliciousbob** [comment]
I changed some settings on my own and made a pull request,
I added a bg-color to the drop-down list of colors:
https://cloud.githubusercontent.com/assets/13135271/8670544/4c0741f0-2a1e-11e5-9e89-7828bbefa55c.jpg

It's not the finest coding, but it works for me and helps me a bit :)

**Comment by oxydron** [comment]
I liked the @deliciousbob solution :D
Maybe, on future, add a user option to change this color pallete to a daltonic mode.

Nice job

**Comment by sah-anshu** [comment]
+1

**Comment by fguillot** [comment]
I changed the color picker in master, that looks like that now:

![color-picker](https://cloud.githubusercontent.com/assets/323546/9701654/6ecf76b4-5401-11e5-8a4e-11eae98e1082.png)
