### ISSUE TITLE
[Bug | Dev-Version] Swimlane takes whole Brwser Window

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#1105]
In the actual master (dev version):

![kb1](https://cloud.githubusercontent.com/assets/1961634/9294111/6e5a0cbc-4443-11e5-81aa-e7eac330dc9b.PNG)
![kb2](https://cloud.githubusercontent.com/assets/1961634/9294112/6e6f1dfa-4443-11e5-8bb4-919d35fb628e.PNG)

2 Swimlanes with 2 Cards need the height of 2 brwonser windows. Maybe there is something wrong with due new hide column function.

Regards,
Timo

Tested in Chrome and Firefox.

**Comment by fguillot** [comment]
It's the expected behavior at the moment. The columns are the height of the window. I didn't found better solution right now when using multiple swimlanes. Maybe I should set a max height...

It's not related to the "hide column" feature but to the individual vertical scrolling of columns and the fact that before a horizontal scroll-bar was in the middle of the screen when there is no task.

**Comment by cesaric** [comment]
I was about to report the same thing but that it started with commit f04ec07.  I can't figure out what you meant by the "*horizontal scroll-bar was in the middle of the screen*".  Is the goal to set a maximum height for each swimlane so that you can have independent vertical scroll bars for each swimlane?

**Comment by fguillot** [comment]
For the "horizontal scroll-bar was in the middle of the screen", see #949 (not really visible on Mac).

- The goal is to have individual scrolling for each column and fix #949 in the same time, this why there is a column height now, when you have only one swimlane that works fine
- Now, this approach needs to be improved when using multiple swimlanes, so I will probably set a max column height if there are only X (10) number of tasks in a column by example...

**Comment by fguillot** [comment]
I changed that now.

**Comment by kingfisher77** [comment]
Perfect!
One little issue is left - is a column hidden by clicking on the column name the height of the lane is back huge again.

**Comment by fguillot** [comment]
@kingfisher77 just changed that in master

**Comment by BlueTeck** [comment]
That better :D
