### ISSUE TITLE
which database for which use case (sqlite vs mysql)

### ISSUE THREAD

**Issue by thob** [fguillot/kanboard#1299]
any hints on what works best in what kind of environments? I was wondering if mysql offers advantages over sqlite.
Thanks

**Comment by fguillot** [comment]
- sqlite: the performances of sqlite still very good especially if you use a ssd hard-drive, you don't have to manage a database server, backup are super easy just a copy and paste the file...
- mysql: work better if you have a lot of concurrency (lot of users), it's also easier to setup a high-availability system with mysql or postgres...

I didn't do any real-world benchmark yet but I would say sqlite = small team and mysql = large team. 

Otherwise it's just matter of personal preferences and deployment constraints.

**Comment by thob** [comment]
:+1:
