### ISSUE TITLE
Deleting a Column Deletes Closed Tasks Too

### ISSUE THREAD

**Issue by phillc73** [fguillot/kanboard#1318]
Just made an awful error.......

The final column on my Board was named "Completed". Once a task was completed, it was moved to this column. After a review of Completed tasks, they were then closed.

It was felt that the Completed column was a bit of a waste of space, given a crowded board, and tasks should be directly closed when completed, and then the Closed Tasks list reviewed subsequently.

I therefore removed the Completed column. Unfortunately, this also deleted all the Closed Tasks, which had last been held in that column. The history of my project has now largely disappeared.

I feel that deleting a Column should not delete any Closed Tasks which may have been formally associated with it.

**Comment by sparkles645** [comment]
* Sorry for your loss of data.
* Still, you do get a warning - ref screeshot below - and if you've reviewed "Completed tasks" (in previous versions) or the "List" (in v 1 0 1 8) - with closed tasks, you know that the closed tasks are assosciated with the column they were in when they were closed.
* If re-structuring an important board, perhaps a backup of the '\data' folder beforehand is appropriate.
![2015-10-03_11-41-15](https://cloud.githubusercontent.com/assets/10092252/10262379/dbb4a06e-69c4-11e5-86a7-ef789d8bf377.jpg)

**Comment by fguillot** [comment]
Linking this ticket with #439

**Comment by regenduft** [comment]
Could you please update the message, to mention the fact that also closed tasks will simply be deleted?

This is very unexpected. 

When I needed to close 50 or more tasks, I always added a new column named "Close", added a new action named "automatically close tasks when moved onto a column", moved all the tasks, then i deleted the column.

As the old kanboard had no bulk closing option, this was the only way to achieve it in time.


Now I hear that all the closed task have been deleted, which is very unexpected because why should anybody think that a task could be still associated to a column when its closed?!

maybe in recent versions of kanboard this idea is logical, but in old versions, where closed tasks could only be seen in a special list, this is really not logical. 


Yes - we have a daily or more often backup. Yes, we could restore this everything. But how could we get tasks from all the old backups back into the current and up to date kanboard.

This would take much longer than the benefits of having a history of closed tasks would probably save us.


I also do not at all understand why deleting a column needs to delete a task. whats the big problem of having a task with no column?

And if this is a big problem, whats the problem of assigning them all to another column or of just displaying a message like "This column contains xx closed (invisible) tasks, do you really want to delete them?"
