### ISSUE TITLE
Analysis on single task provide inaccurate data

### ISSUE THREAD

**Issue by mtruijen** [fguillot/kanboard#1337]
We are on version 1.0.18.

If we do analysis on a single task, the time spend in each column shown, doesn't make sense at all. Where a task did spent a lot of time in a column, the analysis show only a few seconds. We move tasks between column manually (through the front-end) and through the JSONRPC API's.

**Comment by mtruijen** [comment]
From what I can tell, all moveTaskPosition's performed (move to different column within swimlane) through the JSONRPC are not being recorded in the transistions table. I only see the the transistions (moveTaskPosition) that are performed through the front-end.

**Comment by fguillot** [comment]
A new record is created in the transitions table only if a user session is opened.

A user session is opened only when someone is using the user interface or when someone is using the api with it's own username/password (not when you are using the "admin" api access).

The reason is the transitions table contains the person who does the action (Executer).
