### ISSUE TITLE
Can´t attach Document, current attachments from Kanboard 1.0.18 don´t appear.

### ISSUE THREAD

**Issue by jaceguay** [fguillot/kanboard#1375]
Hi, after trying to update copying the Data folder to the new instalation, the message Can´t insert document appear if I try to attach any Document to my tasks, also previous attachments don´t appear and if I try to download then I gives me a zero sized file. If the attachment was a image the thumbnail don´t appear also.
I´m going back to  1.0.18 and everything goes fine.
At home I have a personal server and installed a fresh 1.0.19 everything works fine there.

**Comment by sparkles645** [comment]
@jaceguay 
Tried the same, it worked fine here with my 1.0.19.

**Comment by jaceguay** [comment]
Actually I had a problem with  OpenLdap, I had to put  libeay32.dll and ssleay32.dll in windows\system to fix it. I don´t understand how it wasn´t affecting 10.0.18 but now everyting works fine, thanks.

**Comment by Chaosmeister** [comment]
We have the same Problem:  
Since migrating (just copying the data folder, like always) from 1.0.18 to 1.0.19, we can not append new screenshots anymore and old screenshots wont be displayed as a preview.  
However, they are opened correctly on clicking "open file".

Server: IIS (Version 8.5.9600.16384) on Windows 8.1 Enterprise.
Browser: Latest Chrome on Windows 8.1.

**Comment by fguillot** [comment]
@Chaosmeister Before Kanboard 1.0.19, thumbnails were generated on the fly, now they are generated during file upload. I added a fallback in the master branch for files uploaded before, the thumbnail will be regenerated if missing.
