### ISSUE TITLE
Using tasks links

### ISSUE THREAD

**Issue by jfrenard** [fguillot/kanboard#1390]
Hello,
sorry if my question seems silly but I don't really understand how taks links work... If I choose "task_2 is blocked by task_1", what is the effect? Or perhaps is it just a label?
Thank you for enlithening me :-)

**Comment by fguillot** [comment]
There is no effect, it's just a relation between 2 tasks with a label.

**Comment by jfrenard** [comment]
Ok, thank you. Perhaps it could be an option in a future development? Some tasks marked with a link "blocked by" couldn't be executed as long as the blocking task isn't completed.

**Comment by wozsoft** [comment]
This issue is related to the discussion about milestone tasks too. #971 
The linked task feature simply creates a relationship between tasks whilst a series of fixed "Automatic Actions" selected at the project level can be used to capture an event and then run an action based on the event.
For example, changing the color of a task when it is moved to another column in the project.

In another post #1401 you said you were using swimlanes to create teams, that is a pretty good solution, we have a similar setup where the the default swimlane is the group/team and then the additional swimlanes are the group/team members. A task is created using the default swimlane and then it assigned to a team member by dragging it to their swimlane.

We also define the team as one project, so if the workflow in the business consists of
1. CAD Team Project
2. Admin Team Project and
3. Production Team Project.
The Production Team can't make the product until the Admin Team have completed documentation and the Admin Team can't complete documentation until the CAD Team have finished the drawings.

So we need to have events and actions based on links between tasks too.

Here is a simple example of how this might work to create a color visual trigger for linked tasks using the scenario outlined above.

1. All tasks are created as red by default, a task is created in the CAD project, one in the Admin Project and one in the Production Project and they are linked as predecessor and successor. eg. "blocks" and "is blocked by" etc.
2. When the task is moved to the last column in a project it triggers 2 events.
(a) The color changes to yellow to indicate it is completed for that team (project) and
(b) the successor task is changed from red to green to indicate to the Admin Team that their task is ready to go.

This makes it simple for each team to quickly see which tasks are ready to be started.
They know how many tasks are in their team "to-do" so they are not surprised by tasks that suddenly appear in their project from another project, all that happens is that tasks are flagged as green when the preceding task has been completed. They then assign the task by dragging it to an members swimlane, then that member drags it to the last column in their swimlane and it triggers the same events in the Production Team's Project Board.

Looking for feedback on this use of Kanboard and how hard it might be to implement.

**Comment by jfrenard** [comment]
hello,
the more I use Kanboard, the more I like it! :-)
I use automatic actions to change color according to the category and swinlanes to manage tasks between teams.
The visual code you mentionned is a really good tip. Perhaps we could have a flag icon to symbolize links between tasks?
