### ISSUE TITLE
[FR] LDAP - Add attribute to bind username

### ISSUE THREAD

**Issue by Herve-M** [fguillot/kanboard#1449]
Hello,

It will be nice, if we can set the attribute used to define the username at user creation.

At first see, the existing implementation use the last RDN. So if you have dn like : "dn: uid=9eca670c-5440-48c0-894e-07e09667b928,ou=user,dc=anorg,dc=org", the username will be the uid..

HerveM

**Comment by fguillot** [comment]
Just by curiosity, can you explain or give an example why you are using a UUID like that? what is the use case? is it something common or very specific to your organization?

**Comment by Herve-M** [comment]
We use UUID because we have a open free/service and at registration we don't ask the first name/last name. Without to forget that user can change his nickname or email, so we don't use it for last RDN. 
I don't think it's common :-/

**Comment by fguillot** [comment]
- If I remember correctly, if you define the constant `LDAP_ACCOUNT_ID` in your config file you can specify the LDAP attribute used to fetch the username instead of using the last RDN.
- If you need to store your external uid, instead of changing the database schema, you can add a new user metadata named by example `ldap_uid`.

Note: I will probably rewrite the authentication/authorization system in the future to allow people to create authentication plugins. That also means existing alternative authentication backend will become plugins (Google, Github, etc..). And specific database fields like github_id will be moved to user metadata (custom fields).

**Comment by fguillot** [comment]
With the last version of the master branch, you must to define the LDAP attribute for the username. So you should not have any development to do, just define the constant `LDAP_USER_ATTRIBUTE_USERNAME`.
