### ISSUE TITLE
.htaccess makes the site inaccessible. 

### ISSUE THREAD

**Issue by lairdf** [fguillot/kanboard#1450]
I was upgrading from 1.0.8 to the most recent version, and I have now found out that when .htaccess exists I get a 500 error for the site.  If I simply remove .htaccess everything works perfectly (without friendly urls, of course).

**Comment by sparkles645** [comment]
similar / related to #1437

**Comment by sortoftone** [comment]
Same probleme here after kanboard update from 1.0.8 to 1.0.19 on Apache server.
Error 500 when .htaccess sits in place.
Runs fine without url-rewriting when .htaccess in kanboard rootdirectory not present.

**Comment by fguillot** [comment]
@lairdf Check the error log of your web server, you will see the exact problem.

**Comment by Zvax** [comment]
Right!

This will sound odd, but consulting the logs was apparently too intelligent a thought for me to stumble on it. Just in case other people have th esame environment:

**On shared hosts**, web host have rules about file permissions, in my case, the server was rejecting serving kanboard's index.php because I somehow clone it to be group writeable.

Removing the group write permission (`chmod g-w index.php` just in case) allows for everything to work flawlessly.

Thanks for a great software Kanboard!
