### ISSUE TITLE
Plugin activation

### ISSUE THREAD

**Issue by polom** [fguillot/kanboard#1464]
I just downloaded 1.0.20 to test as I found that Postmark webhook had been moved to a plugin.
I installed and verified that yes, if I don't use the plugin my Postmark integration is broken.
I got the plugin, then went to install it. Documentation says I have to create a Postmark dir in my plugins dir (which happens to be in root directory).
I do it but Kanboard says I have no plugins. Finally I find a setting in config file, indicating my plugins should be in data/plugins (not plugins), unless I change that setting.
I stick to it, move my Postmark dir there.
Now I have a 500 error : 

PHP Fatal error:  Class '\Kanboard\Plugin\Postmark\Plugin' not found in (...)kanboard/app/Core/Plugin/Loader.php on line 62

I resolved it by moving my Postmark plugin back to the /plugins and changing the config.php setting accordingly.

**Comment by fguillot** [comment]
I understand nothing, what is the problem exactly?

To install a plugin your just have to uncompress the archive in the plugins folder, that's it.

**Comment by polom** [comment]
I did. I unzipped the plugin in the /plugins dir but Kanboard did not detect it
In fact the default config file indicated that the plugins dir was data/plugins so I moved my plugin there.
It was detected but I had a 500 error. I guess something in the plugin relates to the /plugin dir.
I followed that intuition : move the plugin back to /plugins + modified the config file. Everything worked then.

**Comment by jtourt** [comment]
Confirming the issue. I went through the same sequence of events when trying to get plugins working with version 1.0.20.

After performing a new installation and using config.default.php as the initial base for the config.php file, installing a plugin is not as simple as uncompressing the plugin archive into the plugin folder. Because the plugins folder is located at the **root** of the app folder, but by default, the PLUGINS_DIR variable points to the plugin folder being located under the **data** folder.

`// Plugins directory `
`define('PLUGINS_DIR', 'data'.DIRECTORY_SEPARATOR.'plugins'); `


This suggests that the plugins folder should be moved to under the data folder.  But that results in an error.

The fix is to change the PLUGINS_DIR variable in the config.default.php/config.php file to:

`// Plugins directory `
`define('PLUGINS_DIR', 'plugins'); `

**Comment by fguillot** [comment]
It's fixed in master. Thanks.

**Comment by luisriera** [comment]
Hi all,

I have had the same issue with the plugins, I am using ver. 1.0.20.  However, when I changed config.php to:
// Plugins directory
define('PLUGINS_DIR', 'plugins');

I get the following error:  Internal Error: Identifier "applicationAccessMap" is not defined.

I have not been able to fix this issue.  

Any help.
