### ISSUE TITLE
Setting for mailgun - can not send notifications

### ISSUE THREAD

**Issue by Unictu** [fguillot/kanboard#1484]
Hi, I have been trying to setup mailgun 1.0.0 with Kanboard 1.20 as below instruction

SMTP of Mailgun:
define('MAIL_TRANSPORT', 'smtp');
define('MAIL_FROM', 'the mailgun configured sender email');
define('MAIL_SMTP_HOSTNAME', 'smtp.mailgun.org');
define('MAIL_SMTP_PORT', 465); // I also tried 587
define('MAIL_SMTP_USERNAME', 'the mailgun email address');
define('MAIL_SMTP_PASSWORD', 'your_mailgun_password');
define('MAIL_SMTP_ENCRYPTION', 'ssl'); // I also tried tls
Or use their HTTP API (faster than SMTP):

Use API:
define('MAIL_TRANSPORT', 'mailgun');
define('MAILGUN_API_TOKEN', 'key-XXXX');
define('MAILGUN_DOMAIN', 'my mailgun domain.tld'); //I am using original sandbox dormain https://api.mailgun.net/v3/sandboxxxx.mailgun.org
define('MAIL_FROM', 'your mailgun sender email address'); // Postmaster@...

Result: no email, no log event in mailgun. Mailgun account is normal.

Some information in debug log:
[2015-11-20 12:02:32] [debug] Sending email to xxx@xxx.com.au (mailgun)
[2015-11-20 12:02:36] [debug] START_REQUEST=/kanboard/?controller=board&action=check&project_id=1&timestamp=1447981346&_=1447981346224
[2015-11-20 12:02:37] [error] HttpClient: request failed
[2015-11-20 12:02:37] [debug] HttpClient: 
[2015-11-20 12:02:37] [debug] HttpClient: payload=from=................
[2015-11-20 12:02:37] [debug] HttpClient: metadata=NULL
[2015-11-20 12:02:37] [debug] HttpClient: response=

Please help. I lost more than a day for this task already. Thanks for any response.

**Comment by weizenspreu** [comment]
Hi there, do you have PHP 5.6+ running on your server? PHP 5.6 made mandatory certificate verification for TLS connections the default. Unfortunately the SwiftMailer library that's used to send mails is not ready for PHP 5.6.

To change that you have to open the file "./vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php". Within that file you look for the method "_establishSocketConnection()". Within that method you find the following code:

```php
$options = array();
if (!empty($this->_params['sourceIp'])) {
    $options['socket']['bindto'] = $this->_params['sourceIp'].':0';
}
$this->_stream = @stream_socket_client($host.':'.$this->_params['port'], $errno, $errstr, $timeout, STREAM_CLIENT_CONNECT, stream_context_create($options));
```

Between these lines you add some code so that it looks like this:

```php
$options = array();
        if (!empty($this->_params['sourceIp'])) {
    $options['socket']['bindto'] = $this->_params['sourceIp'].':0';
}

//!!! dirty hack to get SMTPS working
$options['ssl']['verify_peer'] = MAIL_SMTP_SSL_VERIFY_PEER;
$options['ssl']['peer_name']   = MAIL_SMTP_SSL_PEER_NAME;
$options['ssl']['ciphers']     = MAIL_SMTP_SSL_CIPHERS;
$options['ssl']['cafile']      = MAIL_SMTP_SSL_CAFILE;

$this->_stream = @stream_socket_client($host.':'.$this->_params['port'], $errno, $errstr, $timeout, STREAM_CLIENT_CONNECT, stream_context_create($options));
```

Now you open up your "./config.php" and add some more configuration lines:

```php
//!!! dirty hack to get SMTPS working
define("MAIL_SMTP_SSL_VERIFY_PEER", true);
define("MAIL_SMTP_SSL_PEER_NAME",   "smtp.mailgun.org");
define("MAIL_SMTP_SSL_CIPHERS",     "HIGH:!aNULL:!eNULL:!3DES:!MD5:!RC4:@STRENGTH");
define("MAIL_SMTP_SSL_CAFILE",      "<path to root certificate>");
```

Now find the root certificate of the CA that issued the TLS certificate of Mailgun.org and place it somewhere. Replace the "<path to root certificate>" value with the chosen filename for the CA root certificate.

More on the issue can be found here: https://github.com/fguillot/kanboard/issues/1408

Hope it helps.

**Comment by fguillot** [comment]
@Unictu Here an example:

With the API:

```php
define('MAIL_FROM', 'postmaster@mydomain.tld');
define('MAIL_TRANSPORT', 'mailgun');
define('MAILGUN_API_TOKEN', 'key-something');
define('MAILGUN_DOMAIN', 'mydomain.tld');
```

Or with SMTP:

```php
define('MAIL_TRANSPORT', 'smtp');
define('MAIL_SMTP_HOSTNAME', 'smtp.mailgun.org');
define('MAIL_SMTP_PORT', 465);
define('MAIL_SMTP_USERNAME', 'postmaster@mydomain.tld');
define('MAIL_SMTP_PASSWORD', 'top secret');
define('MAIL_SMTP_ENCRYPTION', 'tls');
```

**Comment by Unictu** [comment]
Thanks guys
