### ISSUE TITLE
Top horizontal scroll

### ISSUE THREAD

**Issue by GDoukhan** [fguillot/kanboard#1555]
In board view, using several swimlanes, it's really annoying to scroll to the bottom of the page to get the horizontal scroller to go to the left of the board.
Could we have an horizontal scroller at the top of the page in case if the board is too high ?

**Comment by fguillot** [comment]
I cannot really move the position of the scrollbars because it's handled by the browsers and not by the application.

You can also switch in "compact" mode that remove the need to scroll horizontally.

I don't know what kind of device you are using, but many touchpad allow you to scroll horizontally without having to go to the bottom of the page, at least Apple's laptops supports that.
