### ISSUE TITLE
Guidance on server setup and cloud-based version of Kanboard

### ISSUE THREAD

**Issue by psheeramun** [fguillot/kanboard#1578]
Hello,

I have recently come across Kanboard and find this an amazing tool for the team project work we are doing.

I wish to test and use Kanboard in an enterprise environment with a couple of users initially. The challenge is that we cannot easily install new software on our laptops. 

Is there a cloud-based version of Kanboard which we can use or can you advise on the best way for us to set up a server so we can use it soon and hopefully scale the number of users?

Can you also confirm if it is possible to run the server on the same laptop/desktop on which the client is running or does the server always have to be a separate PC?

I would appreciate your guidance, many thanks for your cooperation,

Preetam.

**Comment by bdrayer** [comment]
Hi,

You can test it, with your own kanboard, on Framaboard : https://framaboard.org/

**Comment by psheeramun** [comment]
Hello bdrayer,

Many thanks. This is very useful and I could test it on Framaboard.

Can you please advise regarding the server question if I decide to install kanboard? Does the server have to be a separate device or can it be the same device on which the client will be running.

I presume ideally it needs to be a different PC?

Many thanks, much appreciated,

Preetam.

**Comment by bdrayer** [comment]
Hi,

It's web pages, so you can run a web server supporting PHP (and ideally a MySQL server) on the same computer that the one you are using as client. But because it will need to restart sometimes or that you need to stop it for a reason it's better to have it on a separate machine if you are a team. This machine can be a NAS (QNAP or Synology for example), a server or a simple raspberry Pi if you don't want to have a big computer for it.

why do you want to put it on the same machine? (because you need it when you are on road or because you don't want to have an other computer for it?)

**Comment by psheeramun** [comment]
Hi bdrayer,

Thank you for your reply.

We would like to use it internally on a closed network initially amongst a few team members but at the same time it would be great to have the capability to access it when on the road. In a way we need a balance of keeping it private but at the same time having access to it whilst on the go. Having said that I think using it whilst on the go is not a big requirement at the moment.

I will look into setting up a simple web server based on your suggestions e.g. using Raspberry Pi or a spare PC. 

Do you know if there are plans to have a cloud-based version of kanboard or are these already being achieved by projects such as Framaboard?

Wish you well, thanks,

Preetam.
