### ISSUE TITLE
Bug with the SessionManager when running on FreeBSD

### ISSUE THREAD

**Issue by elnicko** [fguillot/kanboard#1590]
Hi there,

I encountered a minor compatibility bug. Running PHP5.6 on a FreeBSD box. After unzipping the latest kanboard version, there was a runtime error in: app/Core/Session/SessionManager.php.

The engine complained abount something in the lines of: 'session.hash_function' must be existing hash function. sha512 does not exist.

Changing line 103 in app/Core/Session/SessionManager.php solves the problem:
---ini_set('session.hash_function', 'sha512'); 
+++ini_set('session.hash_function', '7'); 

Although some linux boxes such as Ubuntu and Arch are accepting 'sha512', maybe it would be a good idea to leave the value to 7 as per specs.

Cheers,
Elnicko

**Comment by fguillot** [comment]
This issue is now fixed in the master branch.

Using '7' as value doesn't seems to generate the expected length of the session id. PHP on FreeBSD seems to fallback to SHA-1 anyway. It's weird because the function `hash_algos()` return `sha512` correctly under FreeBSD. It's maybe a bug of PHP itself. 

Example of session id:

```
SHA-512: PP7XtYhQG-y-DI5YevOc5NZ22qUmG2y8WJOa7rJqQfEO38iLqWhKK9ny7%2CEbz8R71GNAi0WW9rTF6HqvFtKN82
SHA-1: UUsgC8URKBC0fZTHsL5s-1HSCNa
``` 

So, to have a better compatibility between different platforms, the value is now '1' for Kanboard. 

http://php.net/manual/en/session.configuration.php#ini.session.hash-function

Thanks to report the issue.

**Comment by fguillot** [comment]
Just for information, even under Linux or Mac OS, the value '7' doesn't seems to generate a 'sha512' session id.

**Comment by elnicko** [comment]
This is weird indeed. A spontaneous look at the documentation delivers the opposite statement:

http://php.net/manual/en/function.hash-algos.php
...
[5] => sha256
    [6] => sha384
    [7] => sha512
    [8] => ripemd128
    [9] => ripemd160
...

It might be some other ini setting causing the result to be shortened... Anyway, thank you.

Cheers,
elnicko
