### ISSUE TITLE
Plugin initialisation should be case sensitive

### ISSUE THREAD

**Issue by fbartels** [fguillot/kanboard#1627]
Hi,

I just played around with https://github.com/kanboard/plugin-example-css and noticed the following:

Clone the project to *css* (notice the small letter c)
-> plugin will get loaded, but has no effect (empty skin.css file)

rename folder from *css* to *css-inactive*
-> receive error message "Internal Error: Unable to load this plugin class \Kanboard\Plugin\css-inactive\Plugin"

From this I would says that either the plugin (and all its files) should get loaded regardless of the casing or kanboard should not load the plugin if the folder has a wrong casing (maybe more desirable).

I am currently on 1.0.22, but could find no indicator that this behaviour has changed in 1.0.23.

**Comment by fguillot** [comment]
- When the folder name is lowercase, the skin.css url is not valid anymore, this why the css is not loaded. See: https://github.com/kanboard/plugin-example-css/blob/master/Plugin.php#L11
- If you rename the folder to `css-inactive`, you get an error because PHP cannot load the plugin.php file since the namespace declared in the file don't match with the filesystem.

**Comment by fbartels** [comment]
Hi,

thanks for your feedback. I already knew the mechanics why it did not load, my intention was to have it easier for other users on how to install plugins.
