### ISSUE TITLE
Internal Error: Automatic Action Not Found: TaskAssignColorColumn

### ISSUE THREAD

**Issue by netbuk** [fguillot/kanboard#1636]
Hello,
when i upgrade from v1.0.22 to v1.0.23-fix1, i become this error message:

``Internal Error: Automatic Action Not Found: TaskAssignColorColumn``

Database: SQLite (no MySQL / PostgreSQL available on Server)
I´ve done the update like the documentation.

What´s the problem?

**Comment by jtourt** [comment]
Seems as though the database schema did not update the actions table when you upgraded. 

Here are a couple of options that you can try:

Option 1:
- Make a backup of your current data directory.
- Fall back to the non-fix release.  http://kanboard.net/kanboard-1.0.23.zip  Use the upgrade instructions.
- With 1.0.23 running, verify that the error no longer appears when moving tasks to the column that previously triggered the error.
- If no error, then upgrade to v1.0.23-fix1.

Not sure if this will work because it is unknown why the schema did not get updated when you upgraded from v1.0.22 to v1.0.23-fix1.

Option 2:
- Remove all of the automatic actions that you have defined, and recreate them again manually.

**Comment by netbuk** [comment]
Thank you for yours couple of options, but the first one doesn´t work for me.
I make a clean installation of v1.0.23 and copied the content of the data folder into the newly directory ([Doc Upgrade](http://kanboard.net/documentation/update)).
As soon as I open the website, I get the same error.

I guess I will use the second option. Damn
Thx for help

**Comment by jtourt** [comment]
Option 3:   :)

If you are comfortable opening the database with a program like SQLiteStudio (http://sqlitestudio.pl/), you can try adjusting the database manually.

Open the actions table:
Change the data from:  TaskAssignColorColumn
Change to: \Kanboard\Action\TaskAssignColorColumn

It should look like this:

![sqlite actions2](https://cloud.githubusercontent.com/assets/14179005/12238965/79b2a0f8-b854-11e5-81ed-a145294d892a.png)

**Comment by netbuk** [comment]
Wonderfull. It works.
At 3 projects the path ``\Kanboard\Actions\...`` was missing, for whatever reason.
The issue may be closed
