### ISSUE TITLE
Sorting Cards on Board View doesn't work

### ISSUE THREAD

**Issue by Sean-Donovan** [fguillot/kanboard#1660]
Hello,

When I try to sort cards in a column in the Board view, the cards do not stay in the order I want. They seem to jump around at random from the sequence I'm trying to set up.

Running 
- Kanboard 1.0.23
- PHP 7.0.1
- Apache 2.4
- MySQL 5.6.14 Community

**Comment by jtourt** [comment]
Sorting was badly broken with commit 4003b122d085b58ad7acb31bafa44121ed94c37f and released in v1.0.23.  It's surprising more people haven't noticed yet and commented on the issue here.  Please change the status of this issue to Bug.  (Major bug!)

Consider the following board setup and task moves. All the steps below were done consecutively in the order presented.

![0](https://cloud.githubusercontent.com/assets/14179005/12375856/5b230656-bca4-11e5-885b-302ad3aff7ef.png)

Drag T1 to under T5 (Position 5):

![1](https://cloud.githubusercontent.com/assets/14179005/12375867/9f1f374e-bca4-11e5-9b9d-aa8349b3ac72.png)

Drag T1 to under T2 (Position 2):

![2](https://cloud.githubusercontent.com/assets/14179005/12375875/db328e0c-bca4-11e5-91b8-5016c2f7e44c.png)

Drag T1 to under T4 (Position 4):

![3](https://cloud.githubusercontent.com/assets/14179005/12375879/f99523e6-bca4-11e5-93ac-cc15981fdf89.png)

Drag T1 to under T4 (Position 4) again:

![4](https://cloud.githubusercontent.com/assets/14179005/12375885/268f786a-bca5-11e5-923e-f7faf6cf88cb.png)

Drag T1 to above T2 (Position 1):

![5](https://cloud.githubusercontent.com/assets/14179005/12375891/3f89ed82-bca5-11e5-8b7e-117e330cb520.png)

Drag T1 to under T5 (Position 5):

![6](https://cloud.githubusercontent.com/assets/14179005/12375892/50501286-bca5-11e5-837a-57cbea3c5d12.png)

**Comment by jtourt** [comment]
If the file /app/Model/TaskPosition.php is reverted back to the version from release 1.0.22, sorting works flawlessly again.

**Comment by fguillot** [comment]
I reverted back the last changes until I found the issue.
