### ISSUE TITLE
More than one person who is responsible | Adding observers

### ISSUE THREAD

**Issue by AZimmerhofer** [fguillot/kanboard#1712]
Great tool! Thanks,  Frédéric!

Two ideas: 
First: It would be great to introduce two persons who are responsible for a task. For example: task owner and e.g.a deputy.
Second: Would be great to introduce "oberservers" of tasks. They get a notification if something is finished.

Thanks!

**Comment by bdrayer** [comment]
Hi,

I think it can be seen as a duplicate https://github.com/fguillot/kanboard/issues/1637. Perhaps a possibility to add many users with different functions. But I still think it must be as a form of a plugin.

**Comment by 85pando** [comment]
@bdrayer I think this issue is broader than the the linked one. Solving this one here might solve the other as well.

I just wanted to add this feature request as well.
Some thoughts on this:

* No notification on discussion: If I comment on a ticket noone / someone else is assigned to, I will not be notified of his answer. (Auto add to observer list? Have a box when posting a comment to add to observer list?)
* It should be able to somehow "follow" a task → Observer list.
* I would like to be able to add other persons to the observer list (Maybe only for task creator / project manager)

**Comment by BlueTeck** [comment]
see also #1230

**Comment by fguillot** [comment]
Closing this duplicate.
