### ISSUE TITLE
Getting fatal php error Class '\Kanboard\Action\TaskAssignCurrentUserColumn' not found

### ISSUE THREAD

**Issue by DevOps-Haze** [fguillot/kanboard#1729]
I tried upgrading kanboard today but failed. I did not touch the original kanboard directory under /var/www/html. Not sure why but suddenly I am getting following error while trying to access kanboard url -

**Fatal error: Class'\Kanboard\Action\TaskAssignCurrentUserColumn' not found in /var/www/html/kanboard/app/Model/Action.php on line 323**

Could something have changed ? Has anyone seen this error before ?

**Comment by dmcnaughtan** [comment]
I have the same issue.  Anyone find a fix?

**Comment by BlueTeck** [comment]
Please check https://github.com/fguillot/kanboard/issues/1636

**Comment by jtourt** [comment]
Based on the information provided:

- Tried upgrading kanboard today but failed. 
- Did not touch the original kanboard directory under /var/www/html. 

It sounds as though the problem is that the Kanboard installation is in an inconsistent state, which is confirmed by the error message.  The database schema was updated, but the Kanboard files are an earlier version.

Hopefully you made a database backup prior to attempting to upgrade.

A couple options:

Option 1 - Restore the database back to prior to the upgrade. If the database is restored back, and the files are the same as before, then Kanboard should be back to a working state. 

Option 2 - Rename /var/www/html/kanboard to /var/www/html/kanboard-backup.
               - Unzip the latest release to /var/www/html/kanboard.
               - Copy /var/www/html/kanboard-backup/config.php to /var/www/html/kanboard/

The idea with option 2 is to get the latest release files in the proper place.  The cause of the error message is that /kanboard/app/Action/TaskAssignCurrentUserColumn.php is missing, which you confirmed by saying "I did not touch the original Kanboard directory."   To resolve the error, you will need to have the latest release files in place, or restore back the database.

Not sure why the upgrade might have failed.  Did you receive any error messages?

**Comment by DevOps-Haze** [comment]
Thanks a tonne everyone for your response. I tried Option 2 rather than option 1. Kanboard is back up again. 
Strange thing is I still don't know why the upgrade did not work as I wanted all the latest changes to be implemented on our version of kanboard. I had downloaded the latest zip from Github here and placed it by renaming it as mentioned above and I was getting an error like this - vendor/autoload.php) failed to open stream
