### ISSUE TITLE
Database migration from SQLite to MySQL/MariaDB

### ISSUE THREAD

**Issue by ddeimeke** [fguillot/kanboard#1740]
My Kanboard-Installation is getting bigger and bigger. Thanks for this brillant software!

Now I like to migrate from SQLite to MariaDB.

Do you have any hints how I will be able to achieve this?

**Comment by TabDambrine** [comment]
We achieved this some weeks ago with my team (with a MySQL server, should not be a problem to use the same with MariaDB).


1. First we shot off kanboard to prevent writings in the sqlite file during the process.

2. We then generated a dump with a firefox extension that is able to read sqlite files.

3. We ran this dump to create a database in MySQL call kanboard-old, **NB** We had to be extremely careful with the JSON encoded fields to manage the quote and '\' character correctly and escaped those.

4. We created via Kanboard (by configuring it tu use MySQL) the default kanboard database. This was necessary due to the differences between types in SQLite and MySQL and the fact that the SQLite had some extra columns (due to the lack of ALTER TABLE).

5. Then we used a tool able to compare MySQL databases (Toad if i remember well) that allowed us to convert the kanboard-old to the kanboard schema.

6. We then pointed Kanboard on this database (kanboard-old) to test and when everything was ok, dumped kanboard-old in kanboard and dropped the old one.

 We had some troubles with some characters in descriptions or comments and we needed to escaped them correctly but apart from that all went pretty well, kanboard was upgraded 2 times 1.0.23fix and 1.0.24 without any problem.

Hope this can help you.

**Comment by ddeimeke** [comment]
Thanks a lot for your support. But I was hoping for a more automatic way.

My approach would have been a little different.

1. Create database and create tables with ./app/Schema/Sql/mysql.sql
2. Export all tables to files (one file per table)
3. Import all data to the database from step one.
4. Configure Kanboard to use the new database.

But all of this seems to be some handwork.

Maybe a Kanboard feature like "export kanboard to json" and "import kanboard from json" (or something similar) would be great.

**Comment by fguillot** [comment]
Kanboard doesn't have such feature, you have do it manually at your own risk.

**Comment by oliviermaridat** [comment]
I have disclosed a script for migrating SQLite database to MySQL: https://github.com/oliviermaridat/kanboard-sqlite2mysql. It may help.

**Comment by olegkorol** [comment]
Did someone have the chance to test @oliviermaridat 's script?

**Comment by ddeimeke** [comment]
I completely forgot about this.

Used the script now, working perfectly well. Thanks @oliviermaridat

**Comment by amff1704** [comment]
@ddeimeke  Did you experience an actual improvement of performance by doing this?

**Comment by ddeimeke** [comment]
@amff1704 Yes, there is a great impact on performance, but in the end it depends on your usage scenario. If you have an instance you use only with few people and few projects and tasks, you will most probably not see any performance improvement.
