### ISSUE TITLE
Sorting task comments at taskboard by desc

### ISSUE THREAD

**Issue by JohnBat26** [fguillot/kanboard#1824]
Hello.
When task accumulates many comments, when they don't fit in screen.
May be do sorting it by time (desc) ?

**Comment by fguillot** [comment]
You can already sort comments by date (the link is next to the "Comments" title).

**Comment by JohnBat26** [comment]
1. It is about sorting on taskboard in popup window
2. When I click "change sorting" in task form, I get "Internal Error: Action not implemented" error

**Comment by Chaosmeister** [comment]
:+1: 
I get the same error

Kanboard 1.0.25 on IIS 8.5.9600.16384
Chrome Version 48.0.2564.109 m

**Comment by BlueTeck** [comment]
IIS creates 
`?controller=task&amp;action=show&amp;task_id=279&amp;project_id=9#comments`
instead of:
`?controller=task&action=show&task_id=279&project_id=9#comments`

after this: https://github.com/fguillot/kanboard/blob/bb040cfb78d53696edd63bf256d0fd8ba3ccdbfa/app/Controller/Comment.php#L177

Apache seems to work fine.

**Comment by neurocis** [comment]
+1 KB 1.0.26, on IIS as well, same results as reported by JohnBat26.
URL in my case:
`http://kvm-ca-kelstash.ca.kronos.com/kanboard/?controller=task&amp;action=show&amp;task_id=5004&amp;project_id=1#comments`
(same as BlueTeck's findings).

**Comment by BlueTeck** [comment]
Bug still exists in 1.0.27

**Comment by fguillot** [comment]
It should be fixed in master now.
