### ISSUE TITLE
Database migration from SQLite to Postgres

### ISSUE THREAD

**Issue by FelixDefrance** [fguillot/kanboard#1945]
fguillot, 

As the #1740, i needed to migrate from sqlite to postgres.

To make this migration, i used an amazing tool named "pgloader" availlable [here](http://pgloader.io/). 

We make some improvement in pgloader, to convert your sqlite schema. see [dimitri's git](https://github.com/dimitri/pgloader/issues?utf8=%E2%9C%93&q=+is%3Aissue+author%3AFelixDefrance+)

At the end, it's possible to login into kanboard and navigate, but just in "read only". 

This is the problem now. It's impossible to add new projects, or make a comments, etc..
Writes on db isn't possible. 

Here, this is the postgres logs. I hope it is clearer for you 
```
2016-03-04 11:12:10 CET [13730-1] kanban@kanban ERROR:  lastval is not yet defined in this session
2016-03-04 11:12:10 CET [13730-2] kanban@kanban STATEMENT:  SELECT LASTVAL()
2016-03-04 11:12:10 CET [13730-3] kanban@kanban ERROR:  current transaction is aborted, commands ignored until end of transaction block
2016-03-04 11:12:10 CET [13730-4] kanban@kanban STATEMENT:  DEALLOCATE pdo_stmt_0000000d
```

- Kanboard version: v1.0.26
- Database type and version: postgres 9.4.6-0+deb8u1
- OS: Debian

**Comment by fguillot** [comment]
I don't really support migrations from sqlite to another db because it's a endless source of problems.

**Comment by PeGa** [comment]
@fguillot There are many of us that are locked down using sqlite. I do realize that is my fault for no considering the possible drawbacks of using sqlite beyond speed or consistency. Nevertheless, a long time ago Kanboard stopped being "a little program downloaded from github" and it is now a full blown solution for my everyday organization. It is for personal use! but it still remains as a very important part of my day.

I tried pg_loader and it didn't work for me; half an hour after having converted the database I still was struggling to keep together all the field formats, lenghts and conversions between sqlite and PostgreSQL; I gave up. I tried another solution explained in #1740. It didn't work for me either.

I understand that you don't give support and I understand why you've made that decision; but keep in mind that more and more people will appear asking for a solution. If you don't want to give support for whatever reason it would be, please write a guideline or refer links in the documentation or *some kind* of "no warranty" support for us who need to convert the databases. 

If you think you've got the time, please PLEASE consider writing some kind of export/import engine (to/from json, xml, whatever) in order to easily transport databases from/to any engine possible.

Thank you very much for your time and your awesome contribution to the open source community.

Best regards.

**Comment by oliviermaridat** [comment]
Even if I agree that a full export / import system could be great (especially because it implies that you could export a part of a Kanboard instance A and import it in an already existing Kanboard instance B), I don't think it is something easy to implement.

In the mean time, I am preparing the migration from SQLite to MySQL of a Kanboard in my company. I manage to do it manually and I am working on something more automated. Only the main steps are described at the moment: https://github.com/oliviermaridat/kanboard-sqlite2mysql
