### ISSUE TITLE
'Clone this project' with metadata

### ISSUE THREAD

**Issue by Busfreak** [fguillot/kanboard#2043]
### Expected behaviour

With the action 'Clone this project' it should be possible to clone even the metadata.

### Actual behaviour

No metadate are cloned

![clone metadate](https://cloud.githubusercontent.com/assets/12938119/13983087/e6bbd3f0-f0ed-11e5-8222-e44d8f54ed99.jpg)

**Comment by Trudill** [comment]
Hi,
First, thanks for the amazing job you are doing !

Indeed, it would be nice to add this feature ;) I am on 1.0.41.

I just wanted to add (because, I think it might be related), that the export doesn't have this feature too. (If not, we could export and import to duplicate, so it's kind of logic ;) )

As for the creation of a new project based on another one,, it's the same metadata are not available. (it's kind of logic too)  You have :
Permissions
Categories
Tags
Actions
Tasks

But no Metadata.

Have a nice day
