### ISSUE TITLE
web.config seems broken in IIS 8.5

### ISSUE THREAD

**Issue by Cybergern** [fguillot/kanboard#2063]
On the latest 27th of March release of Kanboard, it doesn't seem like the web.config-file in the root is working properly for IIS 8.5. While this file is in place, all I get is a blank page and am unable to change any configuration options in the IIS manager, getting only error messages about invalid configuration. Once this file is deleted, everything seems to work normally.

**Comment by fguillot** [comment]
The web.config have been updated in the development branch, I just tested with IIS 8.5. Do not forget to install the rewrite module http://www.iis.net/learn/extensions/url-rewrite-module/using-the-url-rewrite-module otherwise IIS will return an error.

The web.config file is necessary only for URL rewriting, you can remove it if you don't need/want this feature.
