### ISSUE TITLE
Internal Error: PHP extension required: "pdo_mysql"

### ISSUE THREAD

**Issue by 1BlackHat** [fguillot/kanboard#2146]
Upon installing Kanboard I expected to "login" and start setting things up.

Instead, I encountered an error which states -- Internal Error: PHP extension required: "pdo_mysql"

I've installed it on a shared host which meets all of the requirements stated on the [requirements page](http://kanboard.net/documentation/mysql-configuration) -- and was instructed by their support team to reach out to you for a solution, as they expect that the php.ini file packaged with the installation is the culprit.

I'd rather not post my URL here on the board -- REALLY need help with this though, as it's well beyond my scope of expertise.

I never made it to a login and/or configuration page -- but can offer this:
- Host specs:  Web Fundament Specs
- Kanboard version:  Stable version (v1.0.27)
- Database type and version:  MariaDB 10.0 / MySQL 5.5
- PHP version:  5.5.34
- Operator OS:  Microsoft Windows 7
- Operator Browser:  Google Chrome - Version 49.0.2623.112 m

**Comment by jtourt** [comment]
The problem is with your hosting environment, not Kanboard.

I'll give you some advice that might help.  Create a new file in the root of your Kanboard directory named phpinfo.php with the following contents:

<?php
phpinfo();
?>

View the page and look for "pdp_mysql".  Check if it is listed on the page and enabled.
http://yourhostname/kanboard/phpinfo.php

**Comment by andyhoyland** [comment]
I've been looking at this and not found a difference between the phpinfo file that @1BlackHat linked to and the phpinfo file on my dev server with Kanboard running no problems. 

If you follow the link to the phpinfo file that 1BlackHat posted you will see he _does_ have pdo_mysql enabled in his hosting environment.

1BlackHat - sorry I don't have any actual useful input on this - did you get it working yet?

**Comment by jtourt** [comment]
Following the link that was posted shows us that the hosting provider has pdo_mysql enabled on their frontend web server.  That's it.  We do not know that 1BlackHat's account is running from that particular server.  Even if his account is running from the same server, it's possible to customize PHP settings per domain/account.  So looking at phpinfo from any place other than the account having the problem tells us nothing.

The most likely scenario is that his web environment does not have pdo_mysql enabled, because that is what Kanboard is telling us after it performs a check.  1BlackHat, run phpinfo() from your web space, in the same folder where Kanboard is installed.

**Comment by 1BlackHat** [comment]
First of all -- **THANKS** to jtourt & andyhoyland for answering -- I was starting to give up hope.

As the pdo_mysql goes, _after_ implementing jtourt's advice -- the resultant phpinfo does show that the pdo_mysql is present -- however, instead of pdo_mysql=enabled is shows pdo_mysql=shared (???).  See the screen capture below for all PDO statements:

![phpinfopic](https://cloud.githubusercontent.com/assets/18570237/14792524/41e8d0be-0ae0-11e6-848b-c315e40f4a4b.png)

As that goes, I'd be happy to share the URL so that this can get resolved -- and also assist what must be legions of users who deal with **shared hosting** environments.  What I don't want is to have the URL floating about in search engine results such as Google, Yahoo, & otherwise (which by the way is how I located this "issues forum" for Kanboard).

That much stated, if there's a way for me to private message and/or email the URL for further troubleshooting, I'd be glad to do so.

**Comment by jtourt** [comment]
Is the "Configure Command" the only place that you see pdo_mysql?   There should be a section further down the page specifically for pdo_mysql.  See screenshot below.  If there is not a section for it, then it is not enabled.  

I notice in the screenshot that you have a php.ini file in the Kanboard folder.  That is the loaded configuration file.  You can probably control enabling pdo_mysql on your own by adjusting that file.  I leave that as an exercise for you using the power of Google.

![image](https://cloud.githubusercontent.com/assets/14179005/14794162/9508f020-0af0-11e6-91a1-d653ae2c2fd4.png)

**Comment by 1BlackHat** [comment]
Jtourt,

Again... thank you so much for being willing to help out with this.  In comparing your screenshot above with the phpinfo file you had me create earlier -- I can see that there is no PDO section stated on it (for additional details, please [see it directly](http://kanboard.bookervision.com/phpinfo.php)).

Further, the php.ini which should be controlling it is attached -- the remote host server group wrote the file, and it's admittedly beyond my technical expertise... so I don't know if it's stated correctly or not -!?!

![php-ini](https://cloud.githubusercontent.com/assets/18570237/14798614/213dc1f8-0afe-11e6-9ae5-43699b8fcc8e.png)

What do you think?

**Comment by jtourt** [comment]
Well, we've come this far, might as well keep going.

It looks as though someone botched the final lines in the php.ini file.  The last two extension directives should be on separate lines.  Like this:

 ```
disable_functions=exec,passthru,shell_exec,system,proc_open,popen,curl_exec,curl_multi_exec,parse_ini_file,show_source
extension=pdo.so
extension=pdo_mysql.so
```

Open the php.ini file in a text editor, and add in some carriage returns so that the extension directives are on separate lines.

**Comment by 1BlackHat** [comment]
Revised php.ini as advised -- to no avail... still results in the same error.  As that goes, please see the [php.ini](http://kanboard.bookervision.com/php.ini) file to see that the corrections were implemented in the right way.

**Comment by jtourt** [comment]
Try removing the extension_dir line.

If that doesn't work, try renaming the php.ini file to something else; php.ini.old
I'm curious what happens with the file renamed.

**Comment by 1BlackHat** [comment]
Tried removing the extension_dir = ./ and that resulted in the following error:

"Internal Error: SQLSTATE[HY000] [1045] Access denied for user 'u4756150_kantest'@'localhost' (using password: YES)"

Is there another suggestion, or should I just try renaming the php.ini to php.ini.old?

**Comment by jtourt** [comment]
It's working now.  Check the php info link and you'll see pdo_mysql is now enabled.  That's why you have now progressed to a MySQL error.  It is trying to connect to MySQL, but you have not properly configured the user for the database.

1BlackHat, I've taken you far along the journey, but I must bid you farewell.  As has been demonstrated, you are running into problems with your environment -- not Kanboard problems.  There is much to learn with PHP and MySQL.  I wish you the best of luck on your journey.   - Jason.

**Comment by 1BlackHat** [comment]
Jason,

... and please note my gratitude for your assistance -- Most Appreciated.

**Comment by andyhoyland** [comment]
Nicely done! Hope you got the database connected...

**Comment by 1BlackHat** [comment]
@andyhoyland 

# Yes!!!

...a bit of to and fro with the remote host support team, and the database connection was achieved. 

Although I initially **expected the Kanboard installation to take 15 or less**, but when all was said and done -- **it took a total of 7 days**.

My situation undoubtedly varied from many who will use Kanboard in a shared hosting environment -- but make no mistake -- **it's not necessarily as simple as it seems**.  Anyone intending to perform this install successfully (at least in a _shared hosting_ environment) should **be prepared to have patience and tenacity**.

In conclusion -- it was JTourt's genius, the remote host support team, and determination on my own behalf to see the install through to the end -- that ultimately equated to SUCCESS.  Where the genius of Frédéric Guillot is concerned...** Kanboard is leaps and bounds above other kanban programs**, is very well thought out, and is **THE BEST** of it's kind where _open source_ is concerned.

In closing (albeit I'm a few weeks out from payday) everyone reading this should _remember_ the countless hours and tireless efforts put into programs like these by brilliant developers who love what they do -- and **DONATE** to support the cause!

I, for one, **applaud Kanboard** and hope to see it remain in the lead ahead of the other contenders!  

Most Appreciatively,
1BlackHat

**Comment by jtourt** [comment]
Cheers.  I'm happy to hear that you were able to get Kanboard working finally.
