### ISSUE TITLE
Roles are set to "User" for every remote (LDAP) user since version 1.0.28

### ISSUE THREAD

**Issue by jgeert1** [fguillot/kanboard#2260]
### Expected behaviour

Using the admin account I can set the roles for each user, but when the user logs in using his ldap crendentials, it's reset to "user".

### Actual behaviour

User roles are "reset" to "user". I do not have the ldap_group_provider configered as I don't want to use ldap groups for the management of the roles. This used to work fine until version 1.0.27, but when I use the latest version, it fails.

### Steps to reproduce

1. have ldap configured without configuring "LDAP _GROUP_PROVIDER" (set to '').
2.
3.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.28
- Database type and version: mysql
- PHP version:5.5
- OS: Windows Server 2012
- Browser: IE and/or Chrome

**Comment by SchmilK** [comment]
Have you tried creating an LDAP group in AD for Managers and Admins and putting those 2 groups in the config.php?

Here is what I did, so I can set who is admin or manager via Active Directory.

`// Set to true if you want to preserve the case
#define('LDAP_USERNAME_CASE_SENSITIVE', false);

// Automatically create user account
//define('LDAP_ACCOUNT_CREATION', true);
define('LDAP_USER_CREATION', true);


// Enables AD group based access rights
define('LDAP_GROUP_ADMIN_DN', 'CN=Kanboard Admins,OU=Admins,OU=Groups,DC=domain,DC=com');
define('LDAP_GROUP_MANAGER_DN', 'CN=Kanboard Managers,OU=Admins,OU=Groups,DC=domain,DC=com');


// Enable LDAP group provider for project permissions
// The end-user will be able to browse LDAP groups from the user interface and allow access to specified projects
define('LDAP_GROUP_PROVIDER', true);

// LDAP Base DN for groups
define('LDAP_GROUP_BASE_DN', 'OU=Groups,DC=domain,DC=com');

// LDAP group filter
// Example for ActiveDirectory: (&(objectClass=group)(sAMAccountName=%s*))
define('LDAP_GROUP_FILTER', '(&(objectClass=group)(sAMAccountName=%s*))');

// LDAP attribute for the group name
define('LDAP_GROUP_ATTRIBUTE_NAME', 'cn');
`

**Comment by jgeert1** [comment]
Thanks for your help, but that's not the solution. I do not want to make use of the AD groups to manage roles. I know how to configure it, so that's not the issue. I would like to make use of the management of the roles as provided by Kanboard (builtin), not the LDAP sync of groups. It was working fine in the previous release (1.0.27).

**Comment by SchmilK** [comment]
It seemed to me that after 1.0.28 ldap configuration over powered local configuration.  So it's possible that the default LDAP role of 'user' is now superseeding what is configured via gui.  

I found this out because I have 2 accounts, one manager and one admin.
Kanboard at 1.0.27
GUI configured as 
**myself** = manager
**_myself** = admin
(Ldap was configured with **myself** = admin and  **_myself** was not in ldap group)  These never really did anything, OR, Kanboard configuration overwrite LDAP configuration.

After updating to Kanboard 1.0.28
**myself** changed from manager to admin when I logged in
**_myself** changed from admin to user when I logged in
Manually changed in Kanboard GUI to make **_myself** the admin, but every time I logged in as **_myself**, it reverted to user
When I updated the LDAP group to put **myself** in managers and **_myself** in admin, then both accounts were correct.

**Comment by StanSiska** [comment]
We came into the same troubles today with Kanboard 1.0.28 and SQLite DB. 
When Administrator account is changed to User, it can't be changed back to Administrator again.

Since we don't have LDAP under control and it's problem not to handle users by ourselves, it would be nice to be able to configure roles via GUI as previously.

Furthermore, database copied from 1.0.28 to earlier versions (tested 1.0.27, 1.0.26) suffers the same problem and reverts every Ldap account to User. How it that possible??

**Comment by jgeert1** [comment]
I've reverted back to version 1.0.27, so it's working again. I'll wait for the next release that will have the fix. If it's not getting fixed, I'll change the code to remove the AD role sync.

**Comment by fguillot** [comment]
This issue is now fixed in the development branch.

Closing duplicate with #2198

**Comment by tortue-geniale** [comment]
Hi, 

I report a same bug about user's rules.

Two weeks ago, i upgraded my apps to 1.0.28.
All users are now 'simple users'. There is no admin user :(.
So it isn't possible to create/configure user's profil and settings' apps. Damned!

For Y Information, i use 'Remote_user'  from request http, to identify user, not LDAP.
In Database, in the tables users:
- all coloumn 'roles' are setting at app_user
- all colomn 'ldap...' are setting at true (1)

I try to update manually my account app_user => app_admin. 
In the IHM, i 've no admin rules. :(

Then i try to use, the local user 'admin'. Pfff, i have after the loggin a red banner 'access denied' for all actions and controllers. :(
Finally I try come back to 1.0.27. And for all user i've the save red banner.

Today i use the 1.0.28, but i can't:
- settings apps
- config profil's user after their first login.

An idea ?
Tks.
