### ISSUE TITLE
Customize Priorities

### ISSUE THREAD

**Issue by iM4rv** [fguillot/kanboard#2385]
### Expected behaviour

I would like to change the Priority. Instead of saying "1", "2"... it's important to say "critical", "high"...

I searched evry php file and the whole mysql db but i couldnt find the setting.

Can you please guide me through it?
![tmp](https://cloud.githubusercontent.com/assets/12135467/16334658/8870ca22-3a02-11e6-8ac3-2a8b3b6c65cf.JPG)

### Configuration

Version: 1.0.30
PHP Version: 5.3.10-1ubuntu3.23
PHP SAPI: apache2handler
OS Version: Linux 2.6.32-45-pve
Datenbanktreiber: mysql
Datenbank Version: 5.5.49-0ubuntu0.12.04.1
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by Busfreak** [comment]
In the projects table the priority values are stored: start (eg. 0), end (eg. 3) and default. These values are numerical and a range. So it is not possible to change them from number to text directly.

You could try to assign your own label to a number and display this text instead of the number.
For this you have to create a plugin saving and editing text values for numerical values for a specific board, eg. in the metadata table. Then you have to overwrite the templates, where the priority is shown, call your own functions to overwrite the numbers coming from the database and so on.

I did something similar overwriting color names:
https://github.com/Busfreak/kanboard-color_filter

Good luck :smile:
