### ISSUE TITLE
Task Priority

### ISSUE THREAD

**Issue by ameeriqbal** [fguillot/kanboard#401]
Hi
Is that good if we can prioritize a task rather than complexity? We can set different priorities like ASAP, High, Low etc and the priorities will be shown along with the task in the board.

**Comment by fguillot** [comment]
In Kanban/scrum, the priority is defined by the position (order in the column) of your task in the board. To keep Kanboard simple I prefer not to add another field for that.

**Comment by SeAlgoAsoma** [comment]
Ouch. This is a very major pain point for me, a complete showstopper which I am very displeased to discover after several days setting this up for use on my server. I can't fathom a "priority" field being considered too complicated a functionality for a task management system—in fact, I would say no task management system could be considered ready for prime time without it, not having it is like saying "task name" or "deadline" or "assignee" fields make the system too complicated. It's that fundamental. I have never in my life heard of a task management system that didn't include it, ever. Priority is a fundamental way human beings manage tasks. How am I supposed to distinguish my "urgent- do now" tasks from my "ok to put off until next week tasks"? Having them in single-file order, one after the other, is not a priority system at all, because priorities don't work like that in a real-life business... or at least, not in mine.  In my work, it is unheard of for tasks line up in 1,2,3 ordinal priority order like that. Visual task order is a very poor mechanism for prioritizing things.  It makes kanboard unusable.

I'm going to have to fork the project and add it myself, I guess... crap. I wanted to be live with this tomorrow, in every other way it's perfect.... I wasn't planning on diving into a bunch of programming tongith. 

It's immensely frustrating to finally find a system that is absolutely perfect, except for one bizarre showstopper bug that the developer insists must be there because the developer treats some carved-in-stone dogma "we can't have priorities!", rather than the users' needs, as the most important need to be served. If you're going to hold anything as a virtual religious belief, man, it should be flexibility, not forcing the users to do it some arbitrary way because some other person somewhere once decided that's how they liked it. 

Color tagging is a poor way of marking priority also. Forcing my users to remember a list of colors as shorthand for labels that don't appear anywhere in the system is ridiculous. Nobody is going to want to use that.

Ok... forking... under extreme protest... what a major drag.

**Comment by BlueTeck** [comment]
There is a priority field since 1.0.25

**Comment by SeAlgoAsoma** [comment]
Where? I can't find it.

**Comment by SeAlgoAsoma** [comment]
Oh, hold it, I guess that's a recent update. Looks like I'm at 1.0.23.

**Comment by BlueTeck** [comment]
![image](https://cloud.githubusercontent.com/assets/1961634/13069984/267b30d4-d489-11e5-8828-f68193320784.png)

**Comment by SeAlgoAsoma** [comment]
Ok. Upgrading was really, really, really bad advice. Like, never tell anyone to do that again. I had at least figured out a way to get it usable. Now I have nothing. The new version is totally broken. White screen. Error log says it's looking for files that are missing. This was a pain, sure, but now it's a complete disaster. 

Seriously. Never tell people they should update. You just hosed me completely.

**Comment by froschdesign** [comment]
@SeAlgoAsoma 
Sorry, but you forgot to read the ["Important things to do before updating"](http://kanboard.net/documentation/update) in documentation!

> Error log says it's looking for files that are missing.

Which files are missing? ([Here is all included.](http://kanboard.net/downloads))

> Never tell people they should update. 

Why?

**Comment by ciroiriarte** [comment]
What's the logic of the priority field?, 1 has the higher priority?, or 3 is the higher priority?
