### ISSUE TITLE
Task Complexity

### ISSUE THREAD

**Issue by dbinagi** [fguillot/kanboard#409]
First of all, amazing tool, so far is working great with the projects of the company i work with.

It could be really useful to see the complexity sum on each column on the board. 

Also all of the analytics are made by task count, but it could be great to have those same Analytics by complexity instead of number of tasks. Maybe it should be something optional or just another column but i think complexity is a more relevant measure that needs to be shown.

Keep up the excelent work

**Comment by jregusci** [comment]
I agree with dbinagi. Since the complexity is a very flexible field, you can use it in different contexts and have an estimate for each column.

In Sales, you coud use the board to map leads en propposals and use the complexity field for the expected revenue of the lead. Having the sum at the top of the column coud give you a quick view of the size of the leads that you have at hand.

**Comment by fguillot** [comment]
It's now available in the development version.

The sum of task complexity can be seen on the right of each column if the value is greater than 0.

![column_score](https://cloud.githubusercontent.com/assets/323546/7037023/317f6bba-dd6a-11e4-83ce-aa774ef6fc24.png)

**Comment by jregusci** [comment]
Great. Thanks!
Are you working on having analytics based on complexity? Having that feature would provide you with a burndown chart based on complexity (story points).

**Comment by fguillot** [comment]
Not yet, but should not be very difficult. I have to record some data in the database to generate the burndown chart easily.

**Comment by GrCOTE7** [comment]
Great evolutions :-) Congratulations !

**Comment by jregusci** [comment]
FGuillot, should we open a new Feature Request for the burndown chart since this one is closed?

**Comment by fguillot** [comment]
yep
