### ISSUE TITLE
 UPDATE project_has_users SET is_owner=1 WHERE project_id=$1

### ISSUE THREAD

**Issue by nboucly** [fguillot/kanboard#513]
I have this error when I upgrade V 1.010 to 1.0.11 (Database :  postgresql)

<i>\Schema\version_21 => SQLSTATE[42804]: Datatype mismatch: 7 ERROR: column "is_owner" is of type boolean but expression is of type integer LINE 1: UPDATE project_has_users SET is_owner=1 WHERE project_id=$1 ^ HINT: You will need to rewrite or cast the expression.</i>

I don't have is_owner column in project_has_user table.

Do you have an idea to correct this problem ?

**Comment by fguillot** [comment]
Ok my bad, I made a typo in the SQL query for the schema migration.

You should be able to fix that by adding a quote around the value 1 in the file `app/Schema/Postgres.php`line 33 like that:

https://github.com/fguillot/kanboard/commit/6ad98cb8551887b6f29b805e1853d314d55bcf06

The fix is in the development version. But if you want to stay on the stable, just can just change the sql query. (http://www.postgresql.org/docs/9.1/static/datatype-boolean.html)

**Comment by nboucly** [comment]
Thank you. It works now
