### ISSUE TITLE
Saving GitLab issue after edit creates a new kaboard task every time

### ISSUE THREAD

**Issue by Kodest** [fguillot/kanboard#527]
I have set up GitLab integration according to http://kanboard.net/documentation/gitlab-webhooks. I edit GitLab issues to add or remove tags but every time I save it a new kanboard task is created. I think this is a bug, please confirm.

**Comment by fguillot** [comment]
Yes, it's a bug. I don't get how I didn't catch that during my tests.

It's fixed in the master branch: https://github.com/fguillot/kanboard/commit/51d77786deae14cfa4a7afbf3b097424db8e187b

Note: For now, there is nothing to handle Gitlab issue update in Kanboard, that will be improved.

Thanks to report that.

**Comment by Kodest** [comment]
OK, it works now. I applied your patch on the current stable version, no more duplicated tasks.

Thanks for the quick fix.

**Comment by BlueTeck** [comment]
Issue could be closed.
