### ISSUE TITLE
Best practices: Swimlanes

### ISSUE THREAD

**Issue by jeffshieldsdev** [fguillot/kanboard#534]
I apologize if this isn't the appropriate forum for this, but I wasn't sure where else to ask.

I'm using Kanboard for personal task management, to handle the requests I receive at work.  Previous to 1.0.11 I had one Project called "Requests" for small, miscellaneous, and ad-hoc requests; and 6 other named Projects for some of the larger on-going projects I'm working on.

This worked well, but since they were all different Projects I couldn't get an single overview of what was on my plate, critical, and due soon.  I had to remember to keep switching between Projects and keep an eye on everything.

I don't think Categories would work well for this segmentation because I'm already using Categories to track which group the requests are for, and there also isn't much visual difference between Categories (beyond assigned color).

With the introduction of Swimlanes, I figured I could create a Swimlane for "Requests" and additional Swimlanes for each of the other major projects I'm working on.

I'm wondering what other users thoughts are on the use of Swimlanes this way.  Is this an acceptable use?  I'm concerned moving to this strategy--even though it works now--might not work in future versions if I'm using them in a way not intended.

Thank you for your insight and recommendations.

**Comment by sparkles645** [comment]
Had the same issue. **Can recommend swimlanes** for this issue, as long as it is sufficient / you can accept having the same columns for all projects that are represented on the board.

**Comment by fguillot** [comment]
Actually there is no convenient way to have a global overview and that need to be improved for next versions.

**Comment by tranquility-base** [comment]
fguillot -- very nice software!!

I'm just setting up kanboard for my sysadmin team (4 persons) and settled on this approach, at least to begin with (each person gets a unique color to identify their tasks). To help support this use of swimlanes, it might be nice to have automatic actions for the event of a task switching swimlanes. One action might be a warning dialog to confirm a swimlane switch, since a task jumping to another project should be rare.
