### ISSUE TITLE
Feature Request: Move to Bootstrap

### ISSUE THREAD

**Issue by ibexcore** [fguillot/kanboard#569]
Move to Bootstrap 3 or similar grid based system to correct mobile view and make it look a little nicer.
I'll be doing this anyway eventually, so if you want this feature, I'll put it as a pull request.
![untitled-4 fw](https://cloud.githubusercontent.com/assets/8057812/5993892/1929c90c-aa57-11e4-991f-10ac7b7091fe.png)

**Comment by BlueTeck** [comment]
:+1:

**Comment by fguillot** [comment]
Sorry, but I don't plan to move to Bootstrap. The mobile view can be improved, I already improved the tablet layout with some responsive css.

Moving to Bootstrap will introduce a new dependency, need to change all the templates, testing again everything for potential bugs... Why Bootstrap? Why not Zurb foundation? Why not just any css grid? or the next cool css framework of the moment? When Bootstrap 4 will be released everything will need to be modified again due to breaking changes.

I want to keep this software simple to use and easy to maintain. There is already so much external dependencies. And personally, I'm tired to see Bootstrap everywhere.

**Comment by ibexcore** [comment]
"or similar grid based system".
I just see it as less of a pain-in-the-ass to use someone elses work instead of yourself.

**Comment by euneuber** [comment]
please make it "theme-able"

**Comment by fguillot** [comment]
What grid system do you recommend? There is thousands of projects for that...

**Comment by progsource** [comment]
maybe http://jeet.gs/ is a nice thing - but only if you want to work with preprocessors ;)

**Comment by ibexcore** [comment]
Whatever grid system you are familiar with (if any).
I personally use bootstrap and then run a grunt task to remove all unused selectors (which is usually a lot). Albeit, it can look like the "generic" website but it allows you to concentrate on the actual code rather than front end trouble.

**Comment by phsc** [comment]
:+1: 
Kanboard indeed could look nicer and be more responsive.
Me personally, I like the Bootstrap design...

**Comment by AlgyTaylor** [comment]
Can I request that Kanboard doesn't use Bootstrap?

Personally I quite like Kanboard's look - nice, simplistic and task-focused. It looks like something you use to get stuff done, rather than trying to be the coolest kid on the block :+1:

**Comment by ibexcore** [comment]
I don't care what CSS framework it uses, as long as it works on both, PC,
tablet and mobile. Use Zurb, Material Design, whatever. As long as it looks
fine on all screen sizes.

On 19 February 2015 at 17:01, AlgyTaylor <notifications@github.com> wrote:

> Can I request that Kanboard doesn't use Bootstrap?
>
> Personally I quite like Kanboard's look - nice, simplistic and
> task-focused. It looks like something you use to get stuff done, rather
> than trying to be the coolest kid on the block [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fguillot/kanboard/issues/569#issuecomment-75091297>.
>



-- 
Regards,
James Elliott | Director
james@ibexcore.com | http://ibexcore.com | 01656 837 117

**Comment by bastiao** [comment]
I also would like to have Kanboard with a better UI. Anyone is doing something for it?

**Comment by poVoq** [comment]
Seem to work pretty well on mobile these days, and I like the simplistic look.
IMHO, the lack of a framework should make it easier to include in other projects like owncloud, which is a big plus.

**Comment by bastiao** [comment]
To be honest, the board is a bit hard to manage in mobile (tested in iPhone 5s).

**Comment by SamuelMoraesF** [comment]
Am working in an redesign in the issue #766

**Comment by fguillot** [comment]
If you want to redesign Kanboard or to create a theme, you can use a plugin to do that (only with the development version at the moment).

You can override any templates and use Twitter Bootstrap or anything else if you like too.

More information here:
- https://github.com/fguillot/kanboard/blob/master/doc/plugins.markdown
- https://github.com/kanboard/plugin-example-theme
- https://github.com/kanboard/plugin-example-css

**Comment by nickbe** [comment]
We'll try to enhance the GUI via Plugin and without using Bootstrap like frameworks. 
Right now we had an eye on restya, but only because of the visuals. 

Frédérics concerns about dependencies and his way of keeping the system to a minimum is the best thing about Kanboard. But we also think that if Kanboard comes with a modern, elegant and decent new theme that would make a big difference for a lot of people. 

So we will try to implement a new theme approach on the suggested plugin basis. And Frédéric: I don't like the Bootstrap look either. :)
