### ISSUE TITLE
Can't create project when using Magyar (Hungarian) language

### ISSUE THREAD

**Issue by crash5** [fguillot/kanboard#614]
Hello!
version: 1.0.11

I can't create new project when using Magyar (Hungarian) language for user or the whole site.

**Comment by fguillot** [comment]
It's fixed in the development branch.

The problem was coming from a duplicate column name. In the translation file the column name "Kész" was present two times.

So I renamed the column "Done" to "Csinált" with Google translate.

Diff: https://github.com/fguillot/kanboard/commit/8fde5df4f829e9ea2c3a9262512a34a584e4b4e5

Thanks to report the issue.

**Comment by crash5** [comment]
Thx. I will update the hungarian translation in a week.
