### ISSUE TITLE
[Impr] pause timetracking

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#685]
At the moment the time is recorded between status in process and completed. There should be a possibility to pause/hold time tracking. For example if you work 2 days on a task, the time tracking is running the whole night, but nobody is working during the night.

Or did i missed something?

**Comment by fguillot** [comment]
I plan to add a section for working days/hours for each users. And be able to substract that time from the timesheet.

A button with start/pause/stop will be very useful too.

**Comment by shimza** [comment]
Sounds good

Cheers,

Shimon Friedman 
Mob: 0403067613

**Comment by stefanoco** [comment]
This would be great. For my (our) use case time tracking should have:

- start/stop button in the list of subtasks so that I can select the (sub)task I'm working on right now;
- per-user configurable "off" times (night, lunch, coffee breaks) *but* I can override (pressing again the button??) in case I'm working during those times;
- when I press the "start" button for one subtask, any other sutask already selected as "running" should go into "hold" (not enabled to work at two activities at the same time);
- start/stop button should do *start* and *pause*. Ending a subtask should be done with a different action (*close*?)

**Comment by fguillot** [comment]
@BlueTeck There is now a start/stop button for subtask timer.

**Comment by BlueTeck** [comment]
Thanks :+1:

**Comment by golharam** [comment]
Is there time tracking available for a task and not just a subtask?

**Comment by fguillot** [comment]
@golharam for tasks there is only a field "time spent"
