### ISSUE TITLE
issue with postgresql

### ISSUE THREAD

**Issue by dvfalcao** [fguillot/kanboard#757]
Dear Frédéric,

I'm trying to use your app with postgresql 9.1, but when i was creating the database i've noticed that the table "subtask_time_tracking" has some column names that are considered as reserved words (start, end) by the PostgreSQL parser. So, it doesn't let me create this table. As a consequence, I get a "syntax error near the word 'end'." What can i do? Thanks in advance and congratulations for you project!

**Comment by fguillot** [comment]
Actually, I test the postgres version only with Postgresql 9.4. I don't test with all possible versions.

The column end is escaped with double quote: https://github.com/fguillot/kanboard/blob/master/app/Schema/Postgres.php#L272

It's weird because quoted identifiers seems to be supported since a long time, at least since 8.2 http://www.postgresql.org/docs/8.2/static/sql-syntax-lexical.html

What version of Kanboard do you use?

**Comment by mfoucrier** [comment]
I'm using "postgresql-9.3" on Ubuntu 14.04 server, and I installed Kanboard 1.10, then upgraded to 1.11 then 1.12 without problems

**Comment by vsadriano** [comment]
Mfoucrier,

I've one Kanboard web server with database default settings and I would like to run this with PostgreSQL. I applied the available settings in documentation (http://kanboard.net/documentation/postgresql-configuration), but I received a page blank, instead the login page.

What's the settgins that you applied on Kanbord to run with PostgreSQL? Is there any configuration in addition?

Thanks!

**Comment by fguillot** [comment]
@vsadriano I just tested the current master with a standard Ubuntu 14.04 and with Postgresql 9.3, that should be ok. If you have a blank page that means there is something else wrong, probably a php error a missing extension... check your error logs.
