### ISSUE TITLE
Problems with cummulative flow diagram

### ISSUE THREAD

**Issue by semka** [fguillot/kanboard#805]
Hi there. 
We have a lot of columns on the boards due to complicated workflow. Sorry for russian titles, but I hope actual column names doesn't matter:
![](http://take.ms/zwfig)

After few weeks I looked at flow chart and saw *this*:
![](http://take.ms/VMfIw)
As you can see legend contains not all board's columns. For example there is no Backlog column at all ("Бэклог" in this case).

**Comment by fguillot** [comment]
Do you run this cronjob: https://github.com/fguillot/kanboard/blob/master/docs/cli.markdown#run-daily-project-summaries-calculation ?

**Comment by semka** [comment]
As far as I remember I didn't.

**Comment by fguillot** [comment]
The data to generate this chart come from the table "project_daily_summaries". Each time a task is updated, this table is updated.

So, to understand why your graph is not correct, you can check the values for a given date. You have the number of open tasks per column and per day in that table. I can't really analyze the issue without having access to your database.

It's more accurate to run the cronjob everyday, because the total will be calculated each day for sure even when nothing change on the board.

Note: In the dev version there are a couple of changes about that, by example the total will include closed tasks.

**Comment by semka** [comment]
Thanks for advise about cronjob. I will schedule it right now.

Unfortunaltelly I can't give you access to the entire database, but I can give you project_daily_summaries table dump:  http://lpaste.net/7871208914941902848

Hope this help.

**Comment by fguillot** [comment]
Can you add the dump of the tables `projects` and `columns` so I should be able to regenerate the graph. At least for the project ids 9, 10 and 11. Do you know the project_id of your example?

I suppose that your backlog column have the id 55, no tasks have been counted for that column.

it's probably just a problem with the total column, I mean no calculation have been done for the some days.

Try to run the cronjob just before midnight, after a couple of days the chart should be better.

**Comment by semka** [comment]
I'm afraid column with id 55 is not backlog it is "done".
I have a automatic action which closes issue when dragging to "done" (победа).
Can this cause issues with CFD?

**Comment by fguillot** [comment]
closed tasks were not counted in the total column, now it's the case with the dev version.
