### ISSUE TITLE
Add new user as remote

### ISSUE THREAD

**Issue by epaiva** [fguillot/kanboard#827]
When I add a new user there is no option to mark the user as remote so it can login through LDAP. Right now I need to do this directly in the database.

**Comment by lazki** [comment]
You don't need to create users that way. The first time the LDAP user logins, the kanboard user is created. Pay attention to user details mapping, to sucessfully match Names and emails.

**Comment by epaiva** [comment]
Yes, but then when a new user has to enter the projects I have to add him
in two steps. First asking him to login and, second, adding him to the
projects. It would be helpful to add users to the project faster. Thanks
for you comment.

On Sat, Jul 18, 2015 at 2:20 AM, Federico Lazcano <notifications@github.com>
wrote:

> You don't need to create users that way. The first time the LDAP user
> logins, the kanboard user is created. Pay attention to user details
> mapping, to sucessfully match Names and emails.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fguillot/kanboard/issues/827#issuecomment-122492950>.
>



-- 
Eduardo Spanó Junqueira de Paiva
+55 11 99471 4313

**Comment by fguillot** [comment]
This feature have been implemented in the development branch. Since there is a new option to disable automatic account creation for LDAP users, it's relevant to have a way to add remote users.

Related documentation:
- https://github.com/fguillot/kanboard/blob/master/docs/ldap-authentication.markdown#disable-automatic-account-creation
- https://github.com/fguillot/kanboard/blob/master/docs/user-management.markdown#local-and-remote-users
