### ISSUE TITLE
API when kanboard is behind reverse proxy which already handles basic auth

### ISSUE THREAD

**Issue by blysik** [fguillot/kanboard#865]
Hi,

I have a kanboard behind a reverse proxy which handles https and basic authorization.  However, the jsonrpc call also expects http basic auth with user being jsonrpc, and the api key as the password.

Is there any way I can utilize the API in my configuration?

**Comment by fguillot** [comment]
Do you know if your reverse proxy forward authentication information to the php script in another way?

**Comment by fguillot** [comment]
Maybe the solution is to have the possibility to use another HTTP header for the authentication.

**Comment by blysik** [comment]
Yes, it sets the username used in HTTP_X_FORWARDED_USER.  I use that to get login usernames via:

define('REVERSE_PROXY_USER_HEADER', 'HTTP_X_FORWARDED_USER');

That's all I really know about however.

**Comment by blysik** [comment]
I'm assuming it would forward other heads, if I added them.  Don't know for certain.  Would it be possible to include the API key in the jsonrpc call itself?  I'm not familiar with that side.

**Comment by blysik** [comment]
As a lame hack, could I modify the code somewhere for API calls, and only allow if HTTP_X_FORWARDED_USER matched something I set?  I see this:

$server->authentication(array('jsonrpc' => $container['config']->get('api_token')));

and maybe change jsonrpc to my specific user.  I guess I would have to also include the encoded password there also.

Something like that.

**Comment by fguillot** [comment]
To go trough your reverse proxy, you absolutely need to have a valid end-user account, right?

Why not configure your proxy to not handle authentication for the url `jsonrpc.php`? I don't know if it's possible...

Otherwise, I have to modify the api to handle another header, by example `X-Api-Key: xxxxx`. But your api client also need to define a user/password to be authenticated on your proxy.

**Comment by blysik** [comment]
Yes, to get through the reverse proxy I need a valid single sign on account for the company.  I don't have access to change that.

I have a ruby json-rpc client that I'm using, which I have been able to get through the reverse proxy.  I believe I could add an arbitrary header like X-API-Key.

Here's what I've been doing:
connection = Faraday.new
connection.response :logger, JSONRPC.logger
connection.adapter Faraday.default_adapter
connection.basic_auth(ENV['user'], ENV['pw'])
client = JSONRPC::Client.new('https://deployboard.sd.apple.com/jsonrpc.php', { connection: connection})
client.getAllTasks({project_id: 1, status_id: 1})

From the kanboard side, it gets through, but then fails because the user isn't jsonrpc. 

I believe with Faraday I could also just add an arbitrary header.

**Comment by fguillot** [comment]
With the last master version, you can use a custom http header for the authentication now. See here https://github.com/fguillot/kanboard/blob/master/docs/api-json-rpc.markdown#custom-http-header

I don't know if your ruby client is able to do that, but that works with curl.

Otherwise, since you need to have a valid user to go through your reverse-proxy, just disable temporarily the api authentication until I found a better alternative https://github.com/fguillot/kanboard/blob/master/jsonrpc.php#L7

**Comment by blysik** [comment]
I was able to make it work in ruby like this.  Maybe include in your API examples?

require 'faraday'
conn = Faraday.new(:url => 'https://kanboard.example.com') do |faraday|
  faraday.response :logger
  faraday.headers['X-API-Auth'] = 'XXX' # base64_encode('jsonrpc:API_KEY')
  faraday.basic_auth(ENV['user'], ENV['pw'])  # user/pass to get through basic auth
  faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
end

response = conn.post do |req|
  req.url '/jsonrpc.php'
  req.headers['Content-Type'] = 'application/json'
  req.body = '{ "jsonrpc": "2.0", "id": 1, "method": "getAllTasks" }'
end
puts response.body

**Comment by fguillot** [comment]
Yep, your example is now included in the doc.
