### ISSUE TITLE
unable to create project when application language set to dutch

### ISSUE THREAD

**Issue by def4ce** [fguillot/kanboard#867]
When I switch the application language to dutch and try to create a new project, kanboard is unable to create the project. When I switch it back to English I'm able to create projects.

**Comment by fguillot** [comment]
It's now fixed in the development branch.

The issue was coming from the translation file, the columns "Ready" and "Done" have been translated with the same word "Klaar". So I replaced "Done" by "Afgewerkt", I hope this translation is good enough (I don't speak Dutch).

The fix is there if you don't want to wait the next stable version: https://github.com/fguillot/kanboard/commit/46e9c1fb2ce969caec85df64b2b1d364e39a149c#diff-fc1530b6f5b1b021a1e37421a89a074dL169

Thanks to to report this issue.

**Comment by def4ce** [comment]
Thanks, manually changed it. No issues anymore.
