### ISSUE TITLE
Other license?

### ISSUE THREAD

**Issue by ghostlurker** [fguillot/kanboard#933]
Can you offer this under another license?  The AGPL license is not one any business could use without opening it up to unreasonable risks.  

Possibly even a commercial license or any Of the following:  GPLv2, Apache, MIT, BSD

I'd like to be able to use it,  possibly even pay for it, just can't with the current license.

**Comment by blysik** [comment]
+1 on this.  Apache/MIT/BSD are best.

**Comment by fguillot** [comment]
As a business, which risks do you have with the AGPL license?

**Comment by ghostlurker** [comment]
The AGPL license is basically an extortion license.  It is in used both by patent holding corps (commonly referred to as non practicing entities or patent trolls) as a way to force any company that uses it to either pay an exorbitant sum for commercial support or open source all source code for anything that ever “connects over the network” to the AGPL based code.  This could opens a ludicrous amount of liability for any network based system which even communicates with AGPL code (something yet to be tested in court, but could in theory be extended to include even web browsers).   I know of a company that this has happened to and it effectively devastated them (lost a round of funding, still in a legal battle with the troll who picked up the project).  The ideas that the license was meant to cover (ASP hole) are great, but unfortunately was the implementation was *very* poorly drafted.

My company's legal team flat out refuses the use of any AGPL based open source.  Given the experiences I’m aware of, I completely understand why.

I’d love to give this project a chance and if it worked for us, I’d have no problem even paying a reasonable fee for a commercial license in place of an AGPL license.
But as is, I can’t even download it for testing.

Hope you decide to change the license.

Cheers,
Steve

**Comment by elnicko** [comment]
ghostlurker, 
AFAICS AGPL does not restrict usage, only commercialization. Do you inetnd to use kanboard for your internal routines/project/task management, or do you intend to repackage,further develop, or include in another package and then sell it to your customers? 'Cos AGPL limits you only for the latter.

Cheers

**Comment by ghostlurker** [comment]
No.  We have no plans or desire to provide this as a service (free or paid), or to include it in any other product or service offering.  This would be for internal use only on our internal network (i.e not available via the public internet).  We would, however, like to make integrations to internal tools (such as updates and pulls from our custom internal defect tracking system) to make it truly effective for us.  Given the language in the license and the understanding of our organizations attorney (who actually deals w/ open source quite a lot), the license’s reach is overly broad and can require *any* integrations and any system to which said integrations have been made to be published or potentially subject to claims (putting our internal tools at risk and, potentially, anything that might connect with them).  While this may never be something planned by the current folks owning rights, someone else might later acquire rights and attempt to enforce them (which is something I have knowledge of occurring when a project was “commercialized” by it’s creator, AGPL introduced in a point release, and then later said “commercialization attempt went bankrupt and the rights for the software sold off to a patent troll).  That risk is not something that my organization is willing to accept.  Therefore, the only way my organization can use this is to do so under another license that doesn’t include AGPL reference.  Any of the following could work: a change of the current open source license, availability under more than one license (GPL v2 or AGPL), or under a separate commercial use license.
 
Cheers

**Comment by fguillot** [comment]
I may change the license for the next version because your are not the first one to ask me that.

Basically, I have been contacted by some large companies that want to try the software but they blacklist any versions of the GPL or AGPL licenses. It's always the same story, they ask if I can offer the software under another open source license or under a commercial license to get the OK from their legal team.

Since I'm not ready to offer a commercial license (I mean paid licenses) because I prefer to increase the quality of the open source version at the moment. I don't exclude to release an "enterprise version" in the future if people ask for that...

I will probably choose the MIT license because it's sweet and short, but I want to take some time to think about that. Software licensing is not so easy especially when you are not a lawyer...

If I compare with open source projects like Gitlab, they use the MIT license and they don't seems to have any problem with that.

**Comment by shimza** [comment]
Hi Fred,

The product is amazing, and I am finding usage in so many different ways at
the moment...
Perhaps just as so many people have helped with this product, we can also
help you chose the best license to help keep the quality high and the
product advancing at the pace it has been.

The MIT seems like a god choice at this stage.

**Comment by ghostlurker** [comment]
Licenses that don't pose a problem for us include: MIT, BSD, Apache.

Internal use, GPL v2 requires review, but is likely okay.

Would *love* to give this a spin under any of the above.

Thanks!

**Comment by fguillot** [comment]
I switched Kanboard to the MIT license. The next stable release will be distributed under MIT license, probably in the next couple of days.

@ghostlurker Any feedback for the use of Kanboard in the corporate world is appreciated, that help to improve the software.

**Comment by ghostlurker** [comment]
Happy to!

I’ll be getting it online soon.

Cheers,
Steve

**Comment by mekhanique** [comment]
Hey Frederic,

So far, I’m impressed with what you’ve got here.  Nice work!

Made a quick issue (github enterprise auth - 1053) and seconded another; the LDAP group issue (1027).

A few other features while I’m thinking about it:
1) Create “views” for users based on group membership (i.e. users who belong in X group can only see Y projects)
2) Enable role based access controls and define different levels of users:  admin,  project admin (project settings, backlog grooming), project member (task/subtask update only), project viewer (read only on project plus ability to read charts/graphs), project writer,  ability to create a task, but not see the resulting status of said task until it’s complete - weird, but there are some orgs I’m aware of that have this kind of security restraint)
3) Backlog grooming w/ priority order - in order to feed a “whats up next” configuration
4) Enable corporate branding (color scheme, custom css, logo, etc)
5) Enable banner support (maintenance windows, user communication, legal banners, what not).
6) Provide a support contact point from the login page (can be a URL, email address, etc)
7) Allow a single swim lane in a project to be associated with a github project - giving a larger view to related projects where repos might be separate.

Security:  Get config.php out from the project root (my infosec folks hate having anything like github secrets stored inside the web folder).

Hope this helps.  


Cheers,
Steve

**Comment by mdhooge** [comment]
I know this issue is closed, but… this sounds like FUD to me.

@mekhanique (or others): Can you provide some links about the legal case (patent troll) you are mentioning?

Because, this is not the way I understand it. The additional enforcement (compared to GPL) is only on the server side, never on the clients.
https://falseisnotnull.wordpress.com/2014/07/18/gnu-affero-gpl-license-trying-to-debunking-myths/
