### ISSUE TITLE
Email notification with GMAIL (Google apps)

### ISSUE THREAD

**Issue by jlomba** [fguillot/kanboard#942]
Hello
Congratulations, excellent job done with the Kanboard software. We are beginning to test it on our small business with 10 users.
We tried to configure the Email notification with gmail. Our organization uses gmail (google apps) and our email are username@capilo.com.do.
We have not been successfull on receiving email notifications when tasks are asigned, and tested it in several ways.

We were looking some older posts to see if someone had the same issue, but could not find it. 

Our config.php looks like this. If you could please take a look and help we'll appreciate it.

// Enable/Disable debug
define('DEBUG', true);

// Debug file path
define('DEBUG_FILE', __DIR__.'/data/debug.log');

// Folder for uploaded files, don't forget the trailing slash
define('FILES_DIR', 'data/files/');

// E-mail address for the "From" header (notifications)
define('MAIL_FROM', 'info@capilo.com.do');

// Mail transport to use: "smtp", "sendmail" or "mail" (PHP mail function)
define('MAIL_TRANSPORT', 'smtp');

// SMTP configuration to use when the "smtp" transport is chosen
define('MAIL_SMTP_HOSTNAME', 'smtp-relay.gmail.com');
define('MAIL_SMTP_PORT', 25);
define('MAIL_SMTP_USERNAME', 'username');
define('MAIL_SMTP_PASSWORD', 'super password');
define('MAIL_SMTP_ENCRYPTION', 'ssl'); // Valid values are "null", "ssl" or "tls"

// Sendmail command to use when the transport is "sendmail"
define('MAIL_SENDMAIL_COMMAND', '/usr/sbin/sendmail -bs');

Regards

Jose Lomba (Dominican Republic)

**Comment by fguillot** [comment]
For the troubleshooting:

- Be sure that each user have enabled notifications in their profile
- Be sure that people have defined an email address in their profile
- Check if the users are members of the project
- The person that do the action will not receive any emails
- In the debug file, you can see if there is an error during the process
- You can try another SMTP settings, see https://support.google.com/a/answer/176600?hl=en
By example, you can change the port to 465 instead of 25.

You probably need to configure something in Google Apps settings to enable the SMTP access. 

https://support.google.com/accounts/answer/6010255
https://support.google.com/mail/answer/14257

Finally, just check in the debug file if there is an error message from Google SMTP server, I think they will return the url to their knowledge base.

**Comment by ltajariolli** [comment]
Hi!
How are you?
I've working with Kanboard and I see that issue
But after some time I have fix it
See below:

// E-mail address for the "From" header (notifications)
define('MAIL_FROM', 'senderkaboardunimedjau@gmail');

// Mail transport available: "smtp", "sendmail", "mail" (PHP mail function), "postmark", "mailgun", "sendgrid"
define('MAIL_TRANSPORT', 'smtp');

// SMTP configuration to use when the "smtp" transport is chosen
define('MAIL_SMTP_HOSTNAME', 'smtp.gmail.com');
define('MAIL_SMTP_PORT', 465);
define('MAIL_SMTP_USERNAME', 'senderkanboardunixxxxx@gmail.com');
define('MAIL_SMTP_PASSWORD', 'XXXXXX');
define('MAIL_SMTP_ENCRYPTION', 'ssl'); // Valid values are "null", "ssl" or "tls"

Best regards!
