### ISSUE TITLE
Subtask timer: accumulate time

### ISSUE THREAD

**Issue by stefanoco** [fguillot/kanboard#951]
Should the (recently introduced) subtasks timer "add" time to an already defined "spent" value? I'm thinking of someone performing start/stop several times during a few days while progressing, or manually writing an amount of spent time and them using the timer for an added work.

**Comment by fguillot** [comment]
The subtask timer add time to the time spent (rounded to 15minutes), you can also edit directly the time spent.

**Comment by stefanoco** [comment]
What I notice here (latest from git) is that if I:
- edit "Time spent" for a subtask (2h as an example)
- "Save"
- "Start timer"
- wait a few minutes (<15)
- "Stop timer"

suddenly the Time spent fields gets empty.

**Comment by fguillot** [comment]
I cannot reproduce your issue, tested with postgres and sqlite... Just to be sure did you run composer install when you update from the git repo?

**Comment by stefanoco** [comment]
Using sqlite here... but what I did was:
- install latest stable from zip
- create projects and tasks, test for a while
- on a separate folder cloned latest commit
- composer install
- copied sqlite file under "data" from the other instance
- test latest commit and find this issue

I'm trying with a clean clone today

**Comment by stefanoco** [comment]
Tested here and behaviour is the same: starting / stopping timer in a subtask deletes entered time for the father task. Anything I should try to debug?

**Comment by fguillot** [comment]
I fixed an issue related to that: If you define an task estimate or a task spent the subtask timer was not taking into account the existing values for the task.

Expected behavior:
- The task estimate will be overwritten only if subtasks have estimate defined (sum of subtasks estimates)
- The task time spent will be the sum of all subtasks time spent if defined otherwise the existing value is kept

You can always disable the subtask timer in the application settings if that didn't fit your needs.
