### ISSUE TITLE
Colorcoded priorities?

### ISSUE THREAD

**Issue by poVoq** [fguillot/kanboard#99]
How about having the option of defining priorities similar to categories and have them automatically represented in the card color (instead of free color picking)?

That could also somehow be interlinked with the due date?

**Comment by fguillot** [comment]
The priority is defined by the position on the board, tasks on the top are more important. For me, it's good enough, the software have to be simple.

**Comment by SeAlgoAsoma** [comment]
The software would be simpler if it had a priority field. You made this system it much more complicated by leaving that out. What you're saying here is like refusing to include task titles, descriptions or deadlines and claiming that you're keeping the system "simple" by leaving fundamental things out. If you make your users jump through complicated hoops to do simple things, you're making it more complicated, not simpler. If you add a priority field, rather than make us jump through all kinds of craziness to create a priority scheme, that would make kanboard much simpler.

**Comment by BlueTeck** [comment]
There is a priority field since 1.0.25
